#pragma once

class CBaseDodge{
public:
	//=====DODGE FUNCTIONS FOR EACH HERO=========================================================================
	virtual void DodgeRYZE(KBuffer_Spell) {}				//==1===RYZE========================
	virtual void DodgeGRAGAS(KBuffer_Spell) {}				//==2===GRAGAS======================
	virtual void DodgeGRAGAS_BASETIME(KBuffer_Spell) {}		//==2=B=GRAGAS======================
	virtual void DodgeEZREAL(KBuffer_Spell) {}				//==3===EZREAL======================
	virtual void DodgeCAITLYN(KBuffer_Spell) {}				//==4===CAITLYN=====================
	virtual void DodgeMORGANA(KBuffer_Spell) {}				//==5===MORGANA=====================
	virtual void DodgeCHOGATH(KBuffer_Spell) {}				//==6===CHOGATH=====================
	virtual void DodgeAMUMU(KBuffer_Spell) {}				//==7===AMUMU=======================
	virtual void DodgeGRAVES(KBuffer_Spell) {}				//==8===GRAVES======================
	virtual void DodgeAATROX(KBuffer_Spell) {}				//==9===AATROX======================
	virtual void DodgeAATROX_BASETIME(KBuffer_Spell) {}		//==9=B=AATROX======================
	virtual void DodgeJANNA(KBuffer_Spell) {}				//=10===JANNA=======================
	virtual void DodgeSEJUANI(KBuffer_Spell) {}				//=11===SEJUANI=====================
	virtual void DodgeSEJUANI_BASETIME(KBuffer_Spell) {}	//=11=B=SEJUANI=====================
	virtual void DodgeAHRI(KBuffer_Spell) {}				//=12===AHRI========================
	virtual void DodgeKALISTA(KBuffer_Spell) {}				//=13===KALISTA=====================
	virtual void DodgeJINX(KBuffer_Spell) {}				//=14===JINX========================
	virtual void DodgeMUNDO(KBuffer_Spell) {}				//=15===MUNDO=======================
	virtual void DodgeBLITZCRANK(KBuffer_Spell) {}			//=16===BLITZCRANK==================
	virtual void DodgeBRAND(KBuffer_Spell) {}				//=17===BRAND=======================
	virtual void DodgeBRAUM(KBuffer_Spell) {}				//=18===BRAUM=======================
	virtual void DodgeCORKI(KBuffer_Spell) {}				//=19===CORKI=======================
	virtual void DodgeTAHMKENCH(KBuffer_Spell) {}			//=20===TAHM KENCH==================
	virtual void DodgeFIORA(KBuffer_Spell) {}				//=21===FIORA=======================
	virtual void DodgeJARVAN4(KBuffer_Spell) {}				//=22===JARVAN4=====================
	virtual void DodgeLUX(KBuffer_Spell) {}					//=23===LUX=========================
	virtual void DodgeNIDALEE(KBuffer_Spell) {}				//=24===NIDALEE=====================
	virtual void DodgeOLAF(KBuffer_Spell) {}				//=25===OLAF========================
	virtual void DodgeNAUTILUS(KBuffer_Spell) {}			//=26===NAUTILUS====================
	virtual void DodgeNOCTURNE(KBuffer_Spell) {}			//=27===NOCTURNE====================
	virtual void DodgeMISSFORTUNE(KBuffer_Spell) {}			//=28===MISS FORTUNE================
	virtual void DodgeVARUS(KBuffer_Spell) {}				//=29===VARUS=======================
	virtual void DodgeVEIGAR(KBuffer_Spell) {}				//=30===VEIGAR======================
	virtual void DodgeVELKOZ(KBuffer_Spell) {}				//=31===VELKOZ======================
	virtual void DodgeLUCIAN(KBuffer_Spell) {}				//=32===LUCIAN======================
	virtual void DodgeDRAVEN(KBuffer_Spell) {}				//=33===DRAVEN======================
	virtual void DodgeEKKO(KBuffer_Spell) {}				//=34===EKKO========================
	virtual void DodgeDARIUS(KBuffer_Spell) {}				//=35===DARIUS======================
	virtual void DodgeDARIUS_BASETIME(KBuffer_Spell) {}		//=35=B=DARIUS======================
	virtual void DodgeKARMA(KBuffer_Spell) {}				//=36===KARMA=======================
	virtual void DodgeSIVIR(KBuffer_Spell) {}				//=37===SIVIR=======================
	virtual void DodgeGALIO(KBuffer_Spell) {}				//=38===GALIO=======================
	virtual void DodgeTRISTANA(KBuffer_Spell) {}			//=39===TRISTANA====================
	virtual void DodgeKARTHUS(KBuffer_Spell) {}				//=40===KARTHUS=====================
	virtual void DodgeMALPHITE(KBuffer_Spell) {}			//=41===MALPHITE====================
	virtual void DodgeMALPHITE_BASETIME(KBuffer_Spell) {}	//=41=B=MALPHITE====================
	virtual void DodgeNASUS(KBuffer_Spell) {}				//=42===NASUS=======================
	virtual void DodgeYORICK(KBuffer_Spell) {}				//=43===YORICK======================
	virtual void DodgeLEESIN(KBuffer_Spell) {}				//=44===LEESIN======================
	virtual void DodgeLULU(KBuffer_Spell) {}				//=45===LULU========================
	virtual void DodgeYASUO(KBuffer_Spell) {}				//=46===YASUO=======================
	virtual void DodgeKHAZIX(KBuffer_Spell) {}				//=47===KHAZIX======================
	virtual void DodgeTWISTEDFATE(KBuffer_Spell) {}			//=48===TWISTEDFATE=================
	virtual void DodgeTHRESH(KBuffer_Spell) {}				//=49===THRESH======================
	virtual void DodgeSORAKA(KBuffer_Spell) {}				//=50===SORAKA======================
	virtual void DodgeASHE(KBuffer_Spell) {}				//=51===ASHE========================
	virtual void DodgeSONA(KBuffer_Spell) {}				//=52===SONA========================
	virtual void DodgeFIZZ(KBuffer_Spell) {}				//=53===FIZZ========================
	virtual void DodgeZED(KBuffer_Spell) {}					//=54===ZED=========================
	virtual void DodgeJHIN(KBuffer_Spell) {}				//=55===JHIN========================
	virtual void DodgeXERATH(KBuffer_Spell) {}				//=56===XERATH======================
	virtual void DodgeMALZAHAR(KBuffer_Spell) {}			//=57===MALZAHAR====================
	virtual void DodgeQUINN(KBuffer_Spell) {}				//=58===QUINN=======================
	virtual void DodgeANIVIA(KBuffer_Spell) {}				//=59===ANIVIA======================
	virtual void DodgeZYRA(KBuffer_Spell) {}				//=60===ZYRA========================
	virtual void DodgeELISE(KBuffer_Spell) {}				//=61===ELISE=======================
	virtual void DodgeEVELYNN(KBuffer_Spell) {}				//=62===EVELYNN=====================
	virtual void DodgeDIANA(KBuffer_Spell) {}				//=63===DIANA=======================
	virtual void DodgeKENNEN(KBuffer_Spell) {}				//=64===KENNEN======================
	virtual void DodgePOPPY(KBuffer_Spell) {}				//=65===POPPY=======================
	virtual void DodgeLEBLANC(KBuffer_Spell) {}				//=66===LEBLANC=====================
	virtual void DodgeBARD(KBuffer_Spell) {}				//=67===BARD========================
	virtual void DodgeZILEAN(KBuffer_Spell) {}				//=68===ZILEAN======================
	virtual void DodgeLISSANDRA(KBuffer_Spell) {}			//=69===LISSANDRA===================
	virtual void DodgeSWAIN(KBuffer_Spell) {}				//=70===SWAIN=======================
	virtual void DodgeAURELIONSOL(KBuffer_Spell) {}			//=71===AURELION SOL================
	virtual void DodgeTWITCH(KBuffer_Spell) {}				//=72===TWITCH======================
	virtual void DodgeGNAR(KBuffer_Spell) {}				//=73===GNAR========================
	virtual void DodgeKOGMAW(KBuffer_Spell) {}				//=74===KOGMAW======================
	virtual void DodgeSINGED(KBuffer_Spell) {}				//=75===SINGED======================
	virtual void DodgeCASSIOPEIA(KBuffer_Spell) {}			//=76===CASSIOPEIA==================
	virtual void DodgeHEIMERDINGER(KBuffer_Spell) {}		//=77===HEIMERDINGER================
	virtual void DodgeILLAOI(KBuffer_Spell) {}				//=78===ILLAOI======================
	virtual void DodgeLEONA(KBuffer_Spell) {}				//=79===LEONA=======================
	virtual void DodgeJAYCE(KBuffer_Spell) {}				//=80===JAYCE=======================
	virtual void DodgeKASSADIN(KBuffer_Spell) {}			//=81===KASSADIN====================
	virtual void DodgeSHEN(KBuffer_Spell) {}				//=82===SHEN========================
	virtual void DodgeVIKTOR(KBuffer_Spell) {}				//=83===VIKTOR======================
	virtual void DodgeGANGPLANK(KBuffer_Spell) {}			//=84===GANGPLANK===================
	virtual void DodgeNAMI(KBuffer_Spell) {}				//=85===NAMI========================
	virtual void DodgePHANTHEON(KBuffer_Spell) {}			//=86===PHANTHEON===================
	virtual void DodgeMAOKAI(KBuffer_Spell) {}				//=87===MAOKAI======================
	virtual void DodgeRENGAR(KBuffer_Spell) {}				//=88===RENGAR======================
	virtual void DodgeREKSAI(KBuffer_Spell) {}				//=89===REKSAI======================
	virtual void DodgeSKARNER(KBuffer_Spell) {}				//=90===SKARNER=====================
	virtual void DodgeTARIC(KBuffer_Spell) {}				//=91===TARIC=======================
	virtual void DodgeVI(KBuffer_Spell) {}					//=92===VI==========================
	virtual void DodgeTEEMO(KBuffer_Spell) {}				//=93===TEEMO=======================
	virtual void DodgeURGOT(KBuffer_Spell) {}				//=94===URGOT=======================
	virtual void DodgeORIANNA(KBuffer_Spell) {}				//=95===ORIANNA=====================
	virtual void DodgeRUMBLE(KBuffer_Spell) {}				//=96===RUMBLE======================
	virtual void DodgeSHYVANA(KBuffer_Spell) {}				//=97===SHYVANA=====================
	virtual void DodgeSION(KBuffer_Spell) {}				//=98===SION========================
	virtual void DodgeSYNDRA(KBuffer_Spell) {}				//=99===SYNDRA======================
	virtual void DodgeVLADIMIR(KBuffer_Spell) {}			//100===VLADIMIR====================
	virtual void DodgeZIGGS(KBuffer_Spell) {}				//101===ZIGGS=======================
	virtual void DodgeZAC(KBuffer_Spell) {}					//102===ZAC=========================
	virtual void DodgeANNIE(KBuffer_Spell) {}				//103===ANNIE=======================
	virtual void DodgeMORDEKAISER(KBuffer_Spell) {}			//104===MORDEKAISER=================
	virtual void DodgeTALON(KBuffer_Spell) {}				//105===TALON=======================
	virtual void DodgeRIVEN(KBuffer_Spell) {}				//106===RIVEN=======================
	virtual void DodgeTRYNDAMERE_BASETIME(KBuffer_Spell) {}	//107=B=TRYNDAMERE==================
	virtual void DodgeTALIYAH(KBuffer_Spell) {}				//108===TALIYAH=====================

};
