#pragma once
#include "stdafx.h"
#include "GameData.h"
#include "DataString.h"
#include "Utils.h"

enum HERO_SKILL
{
//==1===RYZE==========================================================================================================
	RYZE_Q_Delay = 250,
	RYZE_Q_Range = 900,
	RYZE_Q_Radius = 55,
	RYZE_Q_MissileSpeed = 1700,
	RYZE_Q_FixedRange = true,
	RYZE_Q_AddHitbox = true,
	RYZE_Q_DangerValue = 2,
	RYZE_Q_IsDangerous = false,
	//RYZE_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	RYZE_Q_CanBeRemoved = true,
	//RYZE_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

//==2===GRAGAS==========================================================================================================
	GRAGAS_Q_Delay = 250,
	GRAGAS_Q_Range = 1100,
	GRAGAS_Q_Radius = 250,
	GRAGAS_Q_MissileSpeed = 1300,
	GRAGAS_Q_FixedRange = false,
	GRAGAS_Q_AddHitbox = true,
	GRAGAS_Q_DangerValue = 2,
	GRAGAS_Q_IsDangerous = false,
	GRAGAS_Q_ExtraDuration = 4500,
	GRAGAS_Q_DontCross = true,

	GRAGAS_E_Delay = 0,
	GRAGAS_E_DelayFlying = 150,
	GRAGAS_E_Range = 650,
	GRAGAS_E_Radius = 200,
	GRAGAS_E_MissileSpeed = 1200,
	GRAGAS_E_FixedRange = true,
	GRAGAS_E_AddHitbox = true,
	GRAGAS_E_DangerValue = 2,
	GRAGAS_E_IsDangerous = false,
	//GRAGAS_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	GRAGAS_E_CanBeRemoved = true,
	GRAGAS_E_ExtraRange = 300,
	//GRAGAS_E_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion},

	GRAGAS_R_Delay = 250,
	GRAGAS_R_DelayFlying = 200,
	GRAGAS_R_Range = 1050,
	GRAGAS_R_Radius = 350,
	GRAGAS_R_MissileSpeed = 1800,
	GRAGAS_R_FixedRange = false,
	GRAGAS_R_AddHitbox = true,
	GRAGAS_R_DangerValue = 5,
	GRAGAS_R_IsDangerous = true,
	//GRAGAS_R_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==3===EZREAL==========================================================================================================
	EZREAL_Q_Delay = 250,
	EZREAL_Q_Range = 1150,
	EZREAL_Q_Radius = 60,
	EZREAL_Q_MissileSpeed = 2000,
	EZREAL_Q_FixedRange = true,
	EZREAL_Q_AddHitbox = true,
	EZREAL_Q_DangerValue = 2,
	EZREAL_Q_IsDangerous = false,
	//EZREAL_Q_ExtraMissileNames = new[] {"EzrealMysticShotPulseMissile"},
	//EZREAL_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	EZREAL_Q_CanBeRemoved = true,
	//EZREAL_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},
	EZREAL_Q_Id = 229,

	EZREAL_W_Delay = 250,
	EZREAL_W_Range = 1000,
	EZREAL_W_Radius = 80,
	EZREAL_W_MissileSpeed = 1600,
	EZREAL_W_FixedRange = true,
	EZREAL_W_AddHitbox = true,
	EZREAL_W_DangerValue = 2,
	EZREAL_W_IsDangerous = false,
	//EZREAL_W_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	EZREAL_R_Delay = 1000,
	EZREAL_R_Range = 20000,
	EZREAL_R_Radius = 160,
	EZREAL_R_MissileSpeed = 2000,
	EZREAL_R_FixedRange = true,
	EZREAL_R_AddHitbox = true,
	EZREAL_R_DangerValue = 3,
	EZREAL_R_IsDangerous = true,
	//EZREAL_R_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},
	EZREAL_R_Id = 245,

//==4===CAITLYN==========================================================================================================
	CAITLYN_Q_Delay = 625,
	CAITLYN_Q_Range = 1250,
	CAITLYN_Q_Radius = 60,
	CAITLYN_Q_MissileSpeed = 2200,
	CAITLYN_Q_FixedRange = true,
	CAITLYN_Q_AddHitbox = true,
	CAITLYN_Q_DangerValue = 2,
	CAITLYN_Q_IsDangerous = false,
	//CAITLYN_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}

	CAITLYN_E_Delay = 125,
	CAITLYN_E_Range = 750,
	CAITLYN_E_Radius = 70,
	CAITLYN_E_MissileSpeed = 1600,
	CAITLYN_E_FixedRange = true,
	CAITLYN_E_AddHitbox = true,
	CAITLYN_E_DangerValue = 1,
	CAITLYN_E_IsDangerous = false,
	CAITLYN_E_CanBeRemoved = true,
	//CAITLYN_E_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

	CAITLYN_W_DangerValue = 1,
	CAITLYN_W_Delay = 1100,
	CAITLYN_W_IsDangerous = false,
	CAITLYN_W_MissileAccel = 0,
	CAITLYN_W_MissileMaxSpeed = 0,
	CAITLYN_W_MissileMinSpeed = 0,
	CAITLYN_W_MissileSpeed = 1000,
	CAITLYN_W_Radius = 75,
	CAITLYN_W_Range = 800,

//==5===MORGANA==========================================================================================================
	MORGANA_Q_Delay = 250,
	MORGANA_Q_DelayFlying = 450,
	MORGANA_Q_Range = 1300,
	MORGANA_Q_Radius = 80,
	MORGANA_Q_MissileSpeed = 1200,
	MORGANA_Q_FixedRange = true,
	MORGANA_Q_AddHitbox = true,
	MORGANA_Q_DangerValue = 3,
	MORGANA_Q_IsDangerous = true,
	//MORGANA_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	MORGANA_Q_CanBeRemoved = true,
	//MORGANA_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

	MORGANA_W_DangerValue = 1,
	MORGANA_W_Delay = 250,
	MORGANA_W_IsDangerous = false,
	MORGANA_W_MissileAccel = 0,
	MORGANA_W_MissileMaxSpeed = 0,
	MORGANA_W_MissileMinSpeed = 0,
	MORGANA_W_MissileSpeed = 1000,
	MORGANA_W_Radius = 175,
	MORGANA_W_Range = 900,

//==6===CHOGATH==========================================================================================================
	CHOGATH_Q_Delay = 1200,
	CHOGATH_Q_Range = 950,
	CHOGATH_Q_Radius = 250,
	//CHOGATH_Q_MissileSpeed = int.MaxValue,
	CHOGATH_Q_FixedRange = false,
	CHOGATH_Q_AddHitbox = true,
	CHOGATH_Q_DangerValue = 3,
	CHOGATH_Q_IsDangerous = false,

	CHOGATH_W_DangerValue = 3,
	CHOGATH_W_Delay = 500,
	CHOGATH_W_IsDangerous = false,
	CHOGATH_W_MissileAccel = 0,
	CHOGATH_W_MissileMaxSpeed = 0,
	CHOGATH_W_MissileMinSpeed = 0,
	CHOGATH_W_MissileSpeed = 1000,
	CHOGATH_W_RadiusCone = 350,
	CHOGATH_W_RadiusLine = 0,
	CHOGATH_W_Range = 660,

//==7===AMUMU==========================================================================================================
	AMUMU_Q_Delay = 210,
	AMUMU_Q_Range = 1100,
	AMUMU_Q_Radius = 80,
	AMUMU_Q_MissileSpeed = 2000,
	AMUMU_Q_FixedRange = true,
	AMUMU_Q_AddHitbox = true,
	AMUMU_Q_DangerValue = 3,
	AMUMU_Q_IsDangerous = true,
	//AMUMU_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	AMUMU_Q_CanBeRemoved = true,
	//AMUMU_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

	AMUMU_R_Delay = 250,
	AMUMU_R_DelayFlying = 200,
	AMUMU_R_Range = 0,
	AMUMU_R_Radius = 550,
	//AMUMU_R_MissileSpeed = int.MaxValue,
	AMUMU_R_FixedRange = true,
	AMUMU_R_AddHitbox = false,
	AMUMU_R_DangerValue = 5,
	AMUMU_R_IsDangerous = true,

//==8===GRAVES==========================================================================================================
	GRAVES_Q_Delay = 250,
	GRAVES_Q_Range_1 = 650,
	GRAVES_Q_Range_2 = 950,
	GRAVES_Q_Radius_1 = 75,
	GRAVES_Q_Radius_2 = 180,
	GRAVES_Q_MissileSpeed = 902,
	GRAVES_Q_FixedRange = true,
	GRAVES_Q_AddHitbox = true,
	GRAVES_Q_DangerValue = 2,
	GRAVES_Q_IsDangerous = false,
	//GRAVES_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	GRAVES_W_Delay = 250,
	GRAVES_W_IsDangerous = false,
	GRAVES_W_MissileAccel = 0,
	GRAVES_W_MissileMaxSpeed = 1650,
	GRAVES_W_MissileMinSpeed = 1650,
	GRAVES_W_MissileSpeed = 1650,
	GRAVES_W_Radius = 225,
	GRAVES_W_Range = 900,

	GRAVES_R_Delay = 250,
	GRAVES_R_Range2 = 1200,
	GRAVES_R_Radius2 = 220,
	GRAVES_R_Range1 = 1050,
	GRAVES_R_Radius1 = 100,
	GRAVES_R_MissileSpeed = 2100,
	GRAVES_R_FixedRange = true,
	GRAVES_R_AddHitbox = true,
	GRAVES_R_DangerValue = 5,
	GRAVES_R_IsDangerous = true,
	//GRAVES_R_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

//==9===AATROX==========================================================================================================
	AATROX_Q_DelayFlying = 150,
	AATROX_Q_Delay = 600,
	AATROX_Q_Range = 650,
	AATROX_Q_Radius = 250,
	AATROX_Q_MissileSpeed = 2000,
	AATROX_Q_FixedRange = false,
	AATROX_Q_AddHitbox = true,
	AATROX_Q_DangerValue = 3,
	AATROX_Q_IsDangerous = true,

	AATROX_E_Delay = 250,
	AATROX_E_Range = 1000,
	AATROX_E_Radius = 150,
	AATROX_E_MissileSpeed = 1250,
	AATROX_E_FixedRange = true,
	AATROX_E_AddHitbox = true,
	AATROX_E_DangerValue = 3,
	AATROX_E_IsDangerous = false,

//=10===JANNA==========================================================================================================
	JANNA_Q_Delay = 250,
	JANNA_Q_Range = 1700,
	JANNA_Q_Radius = 120,
	JANNA_Q_MissileSpeed = 900,
	JANNA_Q_FixedRange = false,
	JANNA_Q_AddHitbox = true,
	JANNA_Q_DangerValue = 2,
	JANNA_Q_IsDangerous = false,
	//JANNA_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//=11===SEJUANI==========================================================================================================
	SEJUANI_Q_DelayFlying = 250,
	SEJUANI_Q_Range = 650,
	SEJUANI_Q_Radius = 150,

	SEJUANI_R_Delay = 250,
	SEJUANI_R_Range = 1175,
	SEJUANI_R_Radius_LINE = 110,
	SEJUANI_R_Radius_CIRCLE = 400,
	SEJUANI_R_MissileSpeed = 1400,
	SEJUANI_R_FixedRange = true,
	SEJUANI_R_AddHitbox = true,
	SEJUANI_R_DangerValue = 3,
	SEJUANI_R_IsDangerous = true,
	SEJUANI_R_CanBeRemoved = true,
	//SEJUANI_R_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},
//=12===AHRI ==========================================================================================================

	AHRI_Q_Delay = 250,
	AHRI_Q_Range = 880,
	AHRI_Q_Radius = 135,
	//AHRI_Q_Radius = 100,
	AHRI_Q_MissileSpeed = 1100,
	AHRI_Q_MissileAccel = 0,
	AHRI_Q_MissileMinSpeed = 1100,
	AHRI_Q_MissileMaxSpeed = 1100,
	AHRI_Q_FixedRange = true,
	AHRI_Q_AddHitbox = true,
	AHRI_Q_DangerValue = 2,
	AHRI_Q_IsDangerous = false,
	AHRI_Q_MissileFollowsUnit = true,
	AHRI_Q_CanBeRemoved = true,
	AHRI_Q_ForceRemove = true,
	//AHRI_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	AHRI_E_Delay = 250,
	AHRI_E_Range = 975,
	AHRI_E_Radius = 80,
	AHRI_E_MissileSpeed = 1200,
	AHRI_E_FixedRange = true,
	AHRI_E_AddHitbox = true,
	AHRI_E_DangerValue = 3,
	AHRI_E_IsDangerous = true,
	//AHRI_E_MissileSpellName = "AhriSeduceMissile",
	//AHRI_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	AHRI_E_CanBeRemoved = true,
	//AHRI_E_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

//=13===KALISTA ==========================================================================================================	

	KALISTA_Q_Delay = 250,
	KALISTA_Q_Range = 1150,
	KALISTA_Q_Radius = 40,
	KALISTA_Q_MissileSpeed = 1200,
	KALISTA_Q_FixedRange = true,
	KALISTA_Q_AddHitbox = true,
	KALISTA_Q_DangerValue = 2,
	KALISTA_Q_IsDangerous = false,
	//KALISTA_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	KALISTA_Q_CanBeRemoved = true,
	//KALISTA_Q_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},	

//=14===JINX ==========================================================================================================		

	JINX_W_Delay = 600,
	JINX_W_Range = 1175,
	JINX_W_Radius = 60,
	JINX_W_MissileSpeed = 3300,
	JINX_W_FixedRange = true,
	JINX_W_AddHitbox = true,
	JINX_W_DangerValue = 3,
	JINX_W_IsDangerous = true,
	//JINX_W_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	JINX_W_CanBeRemoved = true,
	//JINX_W_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

	JINX_R_Delay = 600,
	JINX_R_Range = 25000,
	JINX_R_Radius = 140,
	JINX_R_MissileSpeed = 1700,
	JINX_R_FixedRange = true,
	JINX_R_AddHitbox = true,
	JINX_R_DangerValue = 5,
	JINX_R_IsDangerous = true,
	//JINX_R_EarlyEvade = new[] {EarlyObjects.Allies},
	JINX_R_CanBeRemoved = true,
	//JINX_R_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

//=15===DR.MUNDO ==========================================================================================================

	MUNDO_Q_Delay = 250,
	MUNDO_Q_Range = 1000,
	MUNDO_Q_Radius = 60,
	MUNDO_Q_MissileSpeed = 2000,
	MUNDO_Q_FixedRange = true,
	MUNDO_Q_AddHitbox = true,
	MUNDO_Q_DangerValue = 3,
	MUNDO_Q_IsDangerous = false,
	//MUNDO_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	MUNDO_Q_CanBeRemoved = true,
	//MUNDO_Q_CollisionObjects = new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

//=16===BLITZCRANK ==========================================================================================================	

	BLITZCRANK_Q_Delay = 250,
	BLITZCRANK_Q_Range = 1050,
	BLITZCRANK_Q_Radius = 70,
	BLITZCRANK_Q_MissileSpeed = 1800,
	BLITZCRANK_Q_FixedRange = true,
	BLITZCRANK_Q_AddHitbox = true,
	BLITZCRANK_Q_DangerValue = 4,
	BLITZCRANK_Q_IsDangerous = true,
	//BLITZCRANK_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	BLITZCRANK_Q_CanBeRemoved = true,
	//BLITZCRANK_Q_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

	BLITZCRANK_R_Delay = 250,
	BLITZCRANK_R_Range = 0,
	BLITZCRANK_R_Radius = 600,
	//BLITZCRANK_R_MissileSpeed = int.MaxValue,
	BLITZCRANK_R_FixedRange = true,
	BLITZCRANK_R_AddHitbox = false,
	BLITZCRANK_R_DangerValue = 2,
	BLITZCRANK_R_IsDangerous = false,

//=17===BRAND ==========================================================================================================		

	BRAND_Q_Delay = 250,
	BRAND_Q_Range = 1175,
	BRAND_Q_Radius = 60,
	BRAND_Q_MissileSpeed = 1600,
	BRAND_Q_FixedRange = true,
	BRAND_Q_AddHitbox = true,
	BRAND_Q_DangerValue = 3,
	BRAND_Q_IsDangerous = true,
	//BRAND_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	BRAND_Q_CanBeRemoved = true,
	//BRAND_Q_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

	BRAND_W_Delay = 850,
	BRAND_W_Range = 900,
	BRAND_W_Radius = 240,
	//BRAND_W_MissileSpeed = int.MaxValue,
	BRAND_W_FixedRange = false,
	BRAND_W_AddHitbox = true,
	BRAND_W_DangerValue = 2,
	BRAND_W_IsDangerous = false,

//=18===BRAUM ==========================================================================================================	

	BRAUM_Q_Delay = 250,
	BRAUM_Q_Range = 1000,
	BRAUM_Q_Radius = 70,
	BRAUM_Q_MissileSpeed = 1100,
	BRAUM_Q_FixedRange = true,
	BRAUM_Q_AddHitbox = true,
	BRAUM_Q_DangerValue = 3,
	BRAUM_Q_IsDangerous = true,
	//BRAUM_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	BRAUM_Q_CanBeRemoved = true,
	//BRAUM_Q_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

	BRAUM_R_Delay = 500,
	BRAUM_R_Range = 1250,
	BRAUM_R_Radius = 100,
	BRAUM_R_MissileSpeed = 1400,
	BRAUM_R_FixedRange = true,
	BRAUM_R_AddHitbox = true,
	BRAUM_R_DangerValue = 4,
	BRAUM_R_IsDangerous = true,
	//BRAUM_R_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}

//=19===CORKI ==========================================================================================================

	CORKI_Q_Delay = 300,
	CORKI_Q_Range = 825,
	CORKI_Q_Radius = 250,
	CORKI_Q_MissileSpeed = 1000,
	CORKI_Q_FixedRange = false,
	CORKI_Q_AddHitbox = true,
	CORKI_Q_DangerValue = 2,
	CORKI_Q_IsDangerous = false,
	//CORKI_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}

	CORKI_R1_Delay = 200,// R co 2 loai,loai thuong va qua thu 3 dac biet hon
	CORKI_R1_Range = 1500,
	CORKI_R1_Radius = 60,
	CORKI_R1_MissileSpeed = 2000,
	CORKI_R1_FixedRange = true,
	CORKI_R1_AddHitbox = true,
	CORKI_R1_DangerValue = 2,
	CORKI_R1_IsDangerous = false,
	//CORKI_R1_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	CORKI_R1_CanBeRemoved = true,
	//CORKI_R1_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

	CORKI_R2_Delay = 200,// R co 2 loai,loai thuong va qua thu 3 dac biet hon
	CORKI_R2_Range = 1700,
	CORKI_R2_Radius = 60,
	CORKI_R2_MissileSpeed = 2000,
	CORKI_R2_FixedRange = true,
	CORKI_R2_AddHitbox = true,
	CORKI_R2_DangerValue = 2,
	CORKI_R2_IsDangerous = false,
	//CORKI_R2_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	CORKI_R2_CanBeRemoved = true,
	//CORKI_R2_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

//=20===TAHM KENCH ==========================================================================================================
	TAHM_KENCH_Q_Delay = 250,
	TAHM_KENCH_Q_Range = 850,
	TAHM_KENCH_Q_Radius = 90,
	TAHM_KENCH_Q_MissileSpeed = 2000,
	TAHM_KENCH_Q_FixedRange = true,
	TAHM_KENCH_Q_AddHitbox = true,
	TAHM_KENCH_Q_DangerValue = 3,
	TAHM_KENCH_Q_IsDangerous = true,
	//TAHM_KENCH_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	TAHM_KENCH_Q_CanBeRemoved = true,
	//TAHM_KENCH_Q_CollisionObjects = new[] {CollisionObjectTypes.Minion, CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},
	
	TAHM_KENCH_W_Range = 850,
	TAHM_KENCH_W_Radius = 120,

//=21===FIORA ==========================================================================================================

	FIORA_Q_Delay = 500,
	FIORA_Q_Range = 800,
	FIORA_Q_Radius = 70,
	FIORA_Q_MissileSpeed = 3200,
	FIORA_Q_FixedRange = true,
	FIORA_Q_AddHitbox = true,
	FIORA_Q_DangerValue = 2,
	FIORA_Q_IsDangerous = false,
	//FIORA_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//=22===JARVAN4 ==========================================================================================================	

	JARVAN4_Q1_Delay = 600,// J4 chieu Q co 2 tinh huong
	JARVAN4_Q1_Range = 770,
	JARVAN4_Q1_Radius = 70,
	//JARVAN4_Q1_MissileSpeed = int.MaxValue,
	JARVAN4_Q1_FixedRange = true,
	JARVAN4_Q1_AddHitbox = true,
	JARVAN4_Q1_DangerValue = 3,
	JARVAN4_Q1_IsDangerous = false,

	JARVAN4_Q2_Delay = 250,
	JARVAN4_Q2_Range = 880,
	JARVAN4_Q2_Radius = 70,
	JARVAN4_Q2_MissileSpeed = 1450,
	JARVAN4_Q2_FixedRange = true,
	JARVAN4_Q2_AddHitbox = true,
	JARVAN4_Q2_DangerValue = 3,
	JARVAN4_Q2_IsDangerous = true,

	JARVAN4_E_Delay = 500,
	JARVAN4_E_Range = 860,
	JARVAN4_E_Radius = 175,
	//JARVAN4_E_MissileSpeed = int.MaxValue,
	JARVAN4_E_FixedRange = false,
	JARVAN4_E_AddHitbox = true,
	JARVAN4_E_DangerValue = 2,
	JARVAN4_E_IsDangerous = false,

//=23===LUX ==========================================================================================================	

	LUX_Q_Delay = 250,
	LUX_Q_DelayFlying = 650,
	LUX_Q_Range = 1175,
	LUX_Q_Radius = 80,
	LUX_Q_MissileSpeed = 1200,
	LUX_Q_FixedRange = true,
	LUX_Q_AddHitbox = true,
	LUX_Q_DangerValue = 3,
	LUX_Q_IsDangerous = true,
	//LUX_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	//LUX_Q_CanBeRemoved = true,
	//LUX_Q_CollisionObjects = new[] { CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.

	LUX_E_Delay = 250,
	LUX_E_Range = 1100,
	LUX_E_Radius = 330,
	LUX_E_MissileSpeed = 1300,
	LUX_E_FixedRange = false,
	LUX_E_AddHitbox = true,
	LUX_E_DangerValue = 2,
	LUX_E_IsDangerous = false,
	LUX_E_ExtraDuration = 5500,
	LUX_E_DontCross = true,
	LUX_E_CanBeRemoved = true,
	LUX_E_DisabledByDefault = true,
	//LUX_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	LUX_R_Delay = 1000,
	LUX_R_Range = 3500,
	LUX_R_Radius = 250,
	//LUX_R_MissileSpeed = int.MaxValue,
	LUX_R_FixedRange = true,
	LUX_R_AddHitbox = true,
	LUX_R_DangerValue = 5,
	LUX_R_IsDangerous = true,
	//LUX_R_MissileSpellName = "LuxMaliceCannon",

//=24===NIDALEE ==========================================================================================================	

	NIDALEE_Q_Delay = 250,
	NIDALEE_Q_Range = 1500,
	NIDALEE_Q_Radius = 40,
	NIDALEE_Q_MissileSpeed = 1300,
	NIDALEE_Q_FixedRange = true,
	NIDALEE_Q_AddHitbox = true,
	NIDALEE_Q_DangerValue = 3,
	NIDALEE_Q_IsDangerous = true,
	//NIDALEE_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	NIDALEE_Q_CanBeRemoved = true,
	//NIDALEE_Q_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

	NIDALEE_W_Radius = 80,

	NIDALEE_E_Radius = 310,

//=25===OLAF ==========================================================================================================		

	OLAF_Q_Delay = 250,
	OLAF_Q_Range = 1000,
	OLAF_Q_ExtraRange = 150,
	OLAF_Q_Radius = 90,
	OLAF_Q_MissileSpeed = 1600,
	OLAF_Q_FixedRange = false,
	OLAF_Q_AddHitbox = true,
	OLAF_Q_DangerValue = 2,
	OLAF_Q_IsDangerous = false,
	OLAF_Q_CanBeRemoved = true,
	//OLAF_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}

//=26===NAUTILUS ==========================================================================================================			

	NAUTILUS_Q_Delay = 250,
	NAUTILUS_Q_Range = 1200,
	NAUTILUS_Q_Radius = 90,
	NAUTILUS_Q_MissileSpeed = 2000,
	NAUTILUS_Q_FixedRange = true,
	NAUTILUS_Q_AddHitbox = true,
	NAUTILUS_Q_DangerValue = 3,
	NAUTILUS_Q_IsDangerous = true,
	//NAUTILUS_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects, EarlyObjects.Wall },
	NAUTILUS_Q_CanBeRemoved = true,
	//NAUTILUS_Q_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},//walls?

//=27===NOCTURNE ==========================================================================================================		
	NOCTURNE_Q_Delay = 250,
	NOCTURNE_Q_Range = 1125,
	NOCTURNE_Q_Radius = 60,
	NOCTURNE_Q_MissileSpeed = 1400,
	NOCTURNE_Q_DangerValue = 2,
	NOCTURNE_Q_IsDangerous = false,
	//NOCTURNE_Q_MissileSpellName = "NocturneDuskbringer",
	//NOCTURNE_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}

//=28===MISS FORTUNE ==========================================================================================================			

	MISSFORTUNE_E_Delay = 300,
	MISSFORTUNE_E_DangerValue = 1,
	MISSFORTUNE_E_IsDangerous	= false,
	MISSFORTUNE_E_MissileAccel	= 0,
	MISSFORTUNE_E_MissileMaxSpeed	= 0,
	MISSFORTUNE_E_MissileMinSpeed	= 0,
	MISSFORTUNE_E_MissileSpeed	= 1000,
	MISSFORTUNE_E_Radius	= 350,
	MISSFORTUNE_E_Range	= 1000,

	MISSFORTUNE_R_DangerValue =  5,
	MISSFORTUNE_R_Delay = 250,
	MISSFORTUNE_R_IsDangerous = false,
	MISSFORTUNE_R_MissileAccel = 0,
	MISSFORTUNE_R_MissileMaxSpeed = 0,
	MISSFORTUNE_R_MissileMinSpeed = 0,
	MISSFORTUNE_R_MissileSpeed = 1000,
	MISSFORTUNE_R_Radius = 0,
	MISSFORTUNE_R_Range = 1400,

//==29===VARUS ==========================================================================================================		

	VARUS_Q_Delay = 250,
	VARUS_Q_Range = 1800,
	VARUS_Q_Radius = 70,
	VARUS_Q_MissileSpeed = 1900,
	VARUS_Q_FixedRange = true,
	VARUS_Q_AddHitbox = true,
	VARUS_Q_DangerValue = 2,
	VARUS_Q_IsDangerous = false,
	//VARUS_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	VARUS_E_Delay = 1000,
	VARUS_E_Range = 925,
	VARUS_E_Radius = 235,
	VARUS_E_MissileSpeed = 1750,
	VARUS_E_FixedRange = false,
	VARUS_E_AddHitbox = true,
	VARUS_E_DangerValue = 2,
	VARUS_E_IsDangerous = false,

	VARUS_R_Delay = 250,
	VARUS_R_Range = 1200,
	VARUS_R_Radius = 120,
	VARUS_R_MissileSpeed = 1950,
	VARUS_R_FixedRange = true,
	VARUS_R_AddHitbox = true,
	VARUS_R_DangerValue = 3,
	VARUS_R_IsDangerous = true,
	//VARUS_R_EarlyEvade = new[] {EarlyObjects.Allies},
	VARUS_R_CanBeRemoved = true,
	//VARUS_R_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

//==30===VEIGAR ==========================================================================================================		

	VEIGAR_Q_Delay = 250,
	VEIGAR_Q_Range = 900,
	VEIGAR_Q_Radius = 70,
	VEIGAR_Q_MissileSpeed = 1200,
	VEIGAR_Q_FixedRange = true,
	VEIGAR_Q_AddHitbox = true,
	VEIGAR_Q_DangerValue = 2,
	VEIGAR_Q_IsDangerous = false,
	//VEIGAR_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	//VEIGAR_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	VEIGAR_W_Delay = 1350,
	VEIGAR_W_Range = 900,
	VEIGAR_W_Radius = 225,
	//VEIGAR_W_MissileSpeed = int.MaxValue,
	VEIGAR_W_FixedRange = false,
	VEIGAR_W_AddHitbox = true,
	VEIGAR_W_DangerValue = 2,
	VEIGAR_W_IsDangerous = false,

	VEIGAR_E_Delay = 500,
	VEIGAR_E_Range = 700,
	VEIGAR_E_Radius = 390,
	//VEIGAR_E_MissileSpeed = int.MaxValue,
	VEIGAR_E_FixedRange = false,
	VEIGAR_E_AddHitbox = false,
	VEIGAR_E_DangerValue = 3,
	VEIGAR_E_IsDangerous = true,
	VEIGAR_E_DontAddExtraDuration = true,
	VEIGAR_E_RingRadius = 350,
	VEIGAR_E_ExtraDuration = 3300,
	VEIGAR_E_DontCross = true,

//==31===VELKOZ ==========================================================================================================	

	VELKOZ_Q1_Delay = 250, // Q Velkoz co 2 tinh huong
	VELKOZ_Q1_Range = 1130,
	VELKOZ_Q1_Radius = 60,
	VELKOZ_Q1_MissileSpeed = 1200,
	VELKOZ_Q1_FixedRange = true,
	VELKOZ_Q1_AddHitbox = true,
	VELKOZ_Q1_DangerValue = 2,
	VELKOZ_Q1_IsDangerous = false,
	VELKOZ_Q1_CanBeRemoved = true,
	//VELKOZ_Q1_CollisionObjects =new[]{CollisionObjectTypes.Minion, CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

	VELKOZ_Q2_Delay = 250,
	VELKOZ_Q2_Range = 1050,
	VELKOZ_Q2_Radius = 100,
	VELKOZ_Q2_MissileSpeed = 2100,
	VELKOZ_Q2_FixedRange = true,
	VELKOZ_Q2_AddHitbox = true,
	VELKOZ_Q2_DangerValue = 2,
	VELKOZ_Q2_IsDangerous = false,
	//VELKOZ_Q2_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	VELKOZ_Q2_CanBeRemoved = true,
	//VELKOZ_Q2_CollisionObjects =new[]{CollisionObjectTypes.Minion, CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

	VELKOZ_W_Delay = 250,
	VELKOZ_W_Range = 1200,
	VELKOZ_W_Radius = 88,
	VELKOZ_W_MissileSpeed = 1700,
	VELKOZ_W_FixedRange = true,
	VELKOZ_W_AddHitbox = true,
	VELKOZ_W_DangerValue = 2,
	VELKOZ_W_IsDangerous = false,

	VELKOZ_E_Delay = 500,
	VELKOZ_E_Range = 800,
	VELKOZ_E_Radius = 225,
	VELKOZ_E_MissileSpeed = 1500,
	VELKOZ_E_FixedRange = false,
	VELKOZ_E_AddHitbox = false,
	VELKOZ_E_DangerValue = 2,
	VELKOZ_E_IsDangerous = false,

	VELKOZ_R_Range = 1575,
	VELKOZ_R_Radius = 88,

//==32===LUCIAN==========================================================================================================

    LUCIAN_Q_Delay = 500,
    LUCIAN_Q_Range = 950,
    LUCIAN_Q_Radius = 65,
    //LUCIAN_Q_MissileSpeed = int.MaxValue,
    LUCIAN_Q_FixedRange = true,
    LUCIAN_Q_AddHitbox = true,
    LUCIAN_Q_DangerValue = 2,
    LUCIAN_Q_IsDangerous = false,
	
	LUCIAN_W_Delay = 250,
	LUCIAN_W_DelayFlying = 500,
	LUCIAN_W_Range = 1200,
	LUCIAN_W_Radius2 = 170,
	LUCIAN_W_Radius1 = 80,
	LUCIAN_W_MissileSpeed = 1600,
	LUCIAN_W_FixedRange = true,
	LUCIAN_W_AddHitbox = true,
	LUCIAN_W_DangerValue = 2,
	LUCIAN_W_IsDangerous = false,
	//LUCIAN_W_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},});

	LUCIAN_R_Delay = 500,
	LUCIAN_R_DelayFlying = 1000,
	LUCIAN_R_Range = 1400,
	LUCIAN_R_Radius = 150,
	LUCIAN_R_MissileSpeed = 2800,
	LUCIAN_R_FixedRange = true,
	LUCIAN_R_AddHitbox = true,
	LUCIAN_R_DangerValue = 2,
	LUCIAN_R_IsDangerous = false,
	//LUCIAN_R_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},});

//==33===DRAVEN==========================================================================================================
 
    DRAVEN_E_Delay = 250,
    DRAVEN_E_Range = 1050,
    DRAVEN_E_Radius = 130,
    DRAVEN_E_MissileSpeed = 1600,
    DRAVEN_E_FixedRange = true,
    DRAVEN_E_AddHitbox = true,
    DRAVEN_E_DangerValue = 3,
    DRAVEN_E_IsDangerous = true,
    DRAVEN_E_CanBeRemoved = true,
    //DRAVEN_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}});

    DRAVEN_R_Delay = 400,
    DRAVEN_R_Range = 20000,
    DRAVEN_R_Radius = 160,
    DRAVEN_R_MissileSpeed = 2000,
    DRAVEN_R_FixedRange = true,
    DRAVEN_R_AddHitbox = true,
    DRAVEN_R_DangerValue = 5,
    DRAVEN_R_IsDangerous = true,
   // DRAVEN_R_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}});

//==34===EKKO==========================================================================================================

	EKKO_Q_Delay = 250,
	//EKKO_Q_DelayFlying = 3800,
	EKKO_Q_Range = 1100,
	EKKO_Q_Radius = 80,
	EKKO_Q_MissileSpeed = 1200,
	EKKO_Q_FixedRange = true,
	EKKO_Q_AddHitbox = true,
	EKKO_Q_DangerValue = 4,
	EKKO_Q_IsDangerous = true,
	EKKO_Q_CanBeRemoved = true,
	//EKKO_Q_CollisionObjects =new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall}});

	EKKO_W_Delay = 3750,
	EKKO_W_DelayFlying = 400,
	EKKO_W_Range = 1600,
	EKKO_W_Radius = 375,
	EKKO_W_MissileSpeed = 1650,
	EKKO_W_FixedRange = false,
	EKKO_W_DisabledByDefault = true,
	EKKO_W_AddHitbox = false,
	EKKO_W_DangerValue = 3,
	EKKO_W_IsDangerous = false,
	EKKO_W_CanBeRemoved = true,
                
	EKKO_R_Delay = 250,
	EKKO_R_Range = 1600,
	EKKO_R_Radius = 375,
	EKKO_R_MissileSpeed = 1650,
	EKKO_R_FixedRange = true,
	EKKO_R_AddHitbox = true,
	EKKO_R_DangerValue = 3,
	EKKO_R_IsDangerous = false,
	EKKO_R_CanBeRemoved = true,
             
//==35===DARIUS==========================================================================================================

	DARIUS_Q_Delay = 750,
	DARIUS_Q_DelayFlying = 350,
	DARIUS_Q_Range = 0,
	DARIUS_Q_Radius = 425,
	//DARIUS_Q_MissileSpeed = int.MaxValue, 
	DARIUS_Q_FixedRange = true,
	DARIUS_Q_AddHitbox = true,
	DARIUS_Q_DangerValue = 3,
	DARIUS_Q_IsDangerous = false,
	DARIUS_Q_FollowCaster = true,
	DARIUS_Q_DisabledByDefault = true,

	DARIUS_E_DelayFlying = 150,
	DARIUS_E_Range = 600,
	DARIUS_E_RadiusCone = 280,
	DARIUS_E_RadiusLine = 30,
	//DARIUS_E_MissileSpeed = int.MaxValue,
	DARIUS_E_FixedRange = true,
	DARIUS_E_AddHitbox = false,
	DARIUS_E_DangerValue = 3,
	DARIUS_E_IsDangerous = true,

//==36===KARMA==========================================================================================================

	KARMA_Q1_Delay = 250,
	KARMA_Q1_Range = 1050,
	KARMA_Q1_Radius = 65,
	KARMA_Q1_Radius_2 = 160,
	KARMA_Q1_MissileSpeed = 902,
	KARMA_Q1_FixedRange = true,
	KARMA_Q1_AddHitbox = true,
	KARMA_Q1_DangerValue = 2,
	KARMA_Q1_IsDangerous = false,
	//KARMA_Q1_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	KARMA_Q1_CanBeRemoved = true,
	//KARMA_Q1_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

	KARMA_Q2_Delay = 250,
	KARMA_Q2_Range = 950,
	KARMA_Q2_Radius = 80,
	KARMA_Q2_MissileSpeed = 1700,
	KARMA_Q2_FixedRange = true,
	KARMA_Q2_AddHitbox = true,
	KARMA_Q2_DangerValue = 2,
	KARMA_Q2_IsDangerous = false,
	//KARMA_Q2_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	KARMA_Q2_CanBeRemoved = true,
	//KARMA_Q2_CollisionObjects =new[]{CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},
            
//==37===SIVIR==========================================================================================================
	SIVIR_Q_Delay = 250,
	SIVIR_Q_DelayFlying = 400,
	SIVIR_Q_Range = 1200,
	SIVIR_Q_Radius = 90,
	SIVIR_Q_MissileSpeed = 1350,
	SIVIR_Q_FixedRange = true,
	SIVIR_Q_AddHitbox = true,
	SIVIR_Q_DangerValue = 2,
	SIVIR_Q_IsDangerous = false,
	//SIVIR_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	SIVIR_QReturn_Delay = 0,
	SIVIR_QReturn_Range = 1250,
	SIVIR_QReturn_Radius = 100,
	SIVIR_QReturn_MissileSpeed = 1350,
	SIVIR_QReturn_FixedRange = true,
	SIVIR_QReturn_AddHitbox = true,
	SIVIR_QReturn_DangerValue = 2,
	SIVIR_QReturn_IsDangerous = false,
	SIVIR_QReturn_DisableFowDetection = false,
	SIVIR_QReturn_MissileFollowsUnit = true,
	//SIVIR_QReturn_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==38===GALIO==========================================================================================================
	GALIO_Q_Delay = 250,
	GALIO_Q_Range = 900,
	GALIO_Q_Radius = 200,
	GALIO_Q_MissileSpeed = 1300,
	GALIO_Q_FixedRange = false,
	GALIO_Q_AddHitbox = true,
	GALIO_Q_DangerValue = 2,
	GALIO_Q_IsDangerous = false,
	//GALIO_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},

	GALIO_E_Delay = 250,
	GALIO_E_Range = 1180,
	GALIO_E_Radius = 120,
	GALIO_E_MissileSpeed = 1200,
	GALIO_E_FixedRange = true,
	GALIO_E_AddHitbox = true,
	GALIO_E_DangerValue = 2,
	GALIO_E_IsDangerous = false,
	//GALIO_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	GALIO_R_Delay = 250,
	GALIO_R_DelayFlying = 200,
	GALIO_R_Range = 0,
	GALIO_R_Radius = 550,
	//GALIO_R_MissileSpeed = int.MaxValue,
	GALIO_R_FixedRange = true,
	GALIO_R_AddHitbox = false,
	GALIO_R_DangerValue = 5,
	GALIO_R_IsDangerous = true,

//==39===TRISTANA==========================================================================================================
	TRISTANA_W_Delay = 500,
	TRISTANA_W_Range = 900,
	TRISTANA_W_Radius = 270,
	TRISTANA_W_MissileSpeed = 1500,
	TRISTANA_W_FixedRange = false,
	TRISTANA_W_AddHitbox = true,
	TRISTANA_W_DangerValue = 2,
	TRISTANA_W_IsDangerous = false,

//==40===KARTHUS==========================================================================================================
	KARTHUS_Q_Delay = 625,
	KARTHUS_Q_DelayFlying = 250,
	KARTHUS_Q_Range = 875,
	KARTHUS_Q_Radius = 120,
	//KARTHUS_Q_MissileSpeed = int.MaxValue,
	KARTHUS_Q_FixedRange = false,
	KARTHUS_Q_AddHitbox = true,
	KARTHUS_Q_DangerValue = 2,
	KARTHUS_Q_IsDangerous = false,

//==41===MALPHITE==========================================================================================================
	MALPHITE_R_Delay = 0,
	MALPHITE_R_DelayFlying = 200,
	MALPHITE_R_Range = 1000,
	MALPHITE_R_Radius = 270,
	MALPHITE_R_MissileSpeed = 1500,
	MALPHITE_R_FixedRange = false,
	MALPHITE_R_AddHitbox = true,
	MALPHITE_R_DangerValue = 5,
	MALPHITE_R_IsDangerous = true,

//==42===NASUS==========================================================================================================
	NASUS_R_Radius = 380,

//==43===YORICK==========================================================================================================
	YORICK_W_Radius = 240,

//==44===LEESIN==========================================================================================================
	LEESIN_Q_Delay = 250,
	LEESIN_Q_DelayFlying = 650,
	LEESIN_Q_Range = 1100,
	LEESIN_Q_Radius = 60,
	LEESIN_Q_MissileSpeed = 1800,

//==45===LULU==========================================================================================================
	LULU_Q_Delay = 250,
	//LULU_Q_DelayFlying = 1250,
	LULU_Q_Range = 1000,
	LULU_Q_Radius = 80,
	LULU_Q_MissileSpeed = 1450,
	LULU_Q_FixedRange = true,
	LULU_Q_AddHitbox = true,
	LULU_Q_DangerValue = 2,
	LULU_Q_IsDangerous = false,
	//LULU_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==46===YASUO==========================================================================================================
	YASUO_Q_Delay = 400,
	YASUO_Q_DelayFlying = 100,
	YASUO_Q_Range = 550,
	YASUO_Q_Radius = 30,
	//YASUO_Q_MissileSpeed = int.MaxValue,
	YASUO_Q_FixedRange = true,
	YASUO_Q_AddHitbox = true,
	YASUO_Q_DangerValue = 2,
	YASUO_Q_IsDangerous = true,
	YASUO_Q_Invert = true,

	YASUO_Q2_DelayFlying = 100,
	YASUO_Q2_Range = 550,
	YASUO_Q2_Radius = 30,

	YASUO_Q3_Range = 1100,
	YASUO_Q3_Radius = 90,

//==47===KHAZIX==========================================================================================================
	KHAZIX_W_Delay = 250,
	KHAZIX_W_Range = 1000,
	KHAZIX_W_Radius = 70,
	KHAZIX_W_MissileSpeed = 1700,
	KHAZIX_W_FixedRange = true,
	KHAZIX_W_AddHitbox = true,
	KHAZIX_W_DangerValue = 2,
	KHAZIX_W_IsDangerous = false,
	//KHAZIX_W_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	KHAZIX_W_CanBeRemoved = true,
	KHAZIX_W_MultipleNumber = 3,
	//KHAZIX_W_MultipleAngle = 22f*(float) Math.PI/180,
	//KHAZIX_W_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

	KHAZIX_E_Delay = 250,
	KHAZIX_E_Range = 600,
	KHAZIX_E_Radius = 300,
	KHAZIX_E_MissileSpeed = 1500,
	KHAZIX_E_FixedRange = false,
	KHAZIX_E_AddHitbox = true,
	KHAZIX_E_DangerValue = 2,
	KHAZIX_E_IsDangerous = false,

//==48===TWISTEDFATE==========================================================================================================
	TWISTEDFATE_Q_DelayFlying = 350,
	TWISTEDFATE_Q_Delay = 250,
	TWISTEDFATE_Q_Range = 1450,
	TWISTEDFATE_Q_Radius = 40,
	TWISTEDFATE_Q_MissileSpeed = 1000,
	TWISTEDFATE_Q_FixedRange = true,
	TWISTEDFATE_Q_AddHitbox = true,
	TWISTEDFATE_Q_DangerValue = 2,
	TWISTEDFATE_Q_IsDangerous = false,
	TWISTEDFATE_Q_MultipleNumber = 3,
	//TWISTEDFATE_Q_MultipleAngle = 28*(float) Math.PI/180,
	//TWISTEDFATE_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==49===THRESH==========================================================================================================
	THRESH_Q_Delay = 500,
	THRESH_Q_Range = 1075,
	THRESH_Q_Radius = 60,
	THRESH_Q_MissileSpeed = 1900,
	THRESH_Q_FixedRange = true,
	THRESH_Q_AddHitbox = true,
	THRESH_Q_DangerValue = 3,
	THRESH_Q_IsDangerous = true,
	//THRESH_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	THRESH_Q_CanBeRemoved = true,
	//THRESH_Q_CollisionObjects = new[] {CollisionObjectTypes.Minion, CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

	THRESH_E_Delay = 125,
	THRESH_E_DelayFlying = 1250,
	THRESH_E_Range = 500,
	THRESH_E_Radius = 110,
	THRESH_E_MissileSpeed = 1100,
	THRESH_E_FixedRange = true,
	THRESH_E_AddHitbox = true,
	THRESH_E_DangerValue = 3,
	THRESH_E_IsDangerous = true,
	THRESH_E_Centered = true,

//==50===SORAKA==========================================================================================================
	SORAKA_Q_Radius = 230,
	SORAKA_Q_MissileSpeed = 1750,

	SORAKA_E_Radius = 250,
	SORAKA_E_MissileSpeed = 1750,

//==51===ASHE==========================================================================================================
	ASHE_W_Range = 1250,
	ASHE_W_RadiusCone = 404,
	ASHE_W_RadiusLine = 60,


	ASHE_R_Delay = 250,
	ASHE_R_Range = 25000,
	ASHE_R_Radius = 130,
	ASHE_R_MissileSpeed = 1600,
	ASHE_R_FixedRange = true,
	ASHE_R_AddHitbox = true,
	ASHE_R_DangerValue = 5,
	ASHE_R_IsDangerous = true,
	//ASHE_R_EarlyEvade = new[] {EarlyObjects.Allies},
	ASHE_R_CanBeRemoved = true,
	//ASHE_R_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall}

//==52===SONA==========================================================================================================
	SONA_R_Delay = 250,
	SONA_R_Range = 1000,
	SONA_R_Radius = 150,
	SONA_R_MissileSpeed = 2400,
	SONA_R_FixedRange = true,
	SONA_R_AddHitbox = true,
	SONA_R_DangerValue = 5,
	SONA_R_IsDangerous = true,
	//SONA_R_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==53===FIZZ==========================================================================================================
	FIZZ_R_Delay = 250,
	FIZZ_R_Range = 1600,
	FIZZ_R_Radius_Line = 80,
	FIZZ_R_Radius_Circle = 250,
	FIZZ_R_MissileSpeed = 1350,
	FIZZ_R_FixedRange = false,
	FIZZ_R_AddHitbox = true,
	FIZZ_R_DangerValue = 5,
	FIZZ_R_IsDangerous = true,
	//FIZZ_R_EarlyEvade = new[] {EarlyObjects.Allies},
	//FIZZ_R_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},
	FIZZ_R_CanBeRemoved = true,

//==54===ZED==========================================================================================================
	ZED_Q_Delay = 250,
	ZED_Q_Range = 925,
	ZED_Q_Radius = 50,
	ZED_Q_MissileSpeed = 1700,
	ZED_Q_FixedRange = true,
	ZED_Q_AddHitbox = true,
	ZED_Q_DangerValue = 2,
	ZED_Q_IsDangerous = false,
	//ZED_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==55===JHIN==========================================================================================================
	JHIN_W_Delay = 750,
	JHIN_W_Range = 2550,
	JHIN_W_Radius = 50,
	JHIN_W_MissileSpeed = 5000,
	JHIN_W_FixedRange = true,
	JHIN_W_AddHitbox = true,
	JHIN_W_DangerValue = 3,
	JHIN_W_IsDangerous = true,
	//JHIN_W_EarlyEvade = new[] { EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects },
	JHIN_W_CanBeRemoved = true,
	//JHIN_W_CollisionObjects = new[] { CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall },

	JHIN_E_Radius = 65,

	JHIN_R_Delay = 250,
	JHIN_R_Range = 3500,
	JHIN_R_Radius = 80,
	JHIN_R_MissileSpeed = 5000,
	JHIN_R_FixedRange = true,
	JHIN_R_AddHitbox = true,
	JHIN_R_DangerValue = 3,
	JHIN_R_IsDangerous = true,
	//JHIN_R_EarlyEvade = new[] { EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects },
	JHIN_R_CanBeRemoved = true,
	//JHIN_R_CollisionObjects = new[] { CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall },

//==56===XERATH==========================================================================================================
	XERATH_Q_Delay = 600,
	XERATH_Q_Range = 1600,
	XERATH_Q_Radius = 100,
	//XERATH_Q_MissileSpeed = int.MaxValue,
	XERATH_Q_FixedRange = true,
	XERATH_Q_AddHitbox = true,
	XERATH_Q_DangerValue = 2,
	XERATH_Q_IsDangerous = false,

	XERATH_W_Delay = 700,
	XERATH_W_Range = 1000,
	XERATH_W_Radius = 220,
	//XERATH_W_MissileSpeed = int.MaxValue,
	XERATH_W_FixedRange = false,
	XERATH_W_AddHitbox = true,
	XERATH_W_DangerValue = 2,
	XERATH_W_IsDangerous = false,

	XERATH_E_Delay = 200,
	XERATH_E_Range = 1100,
	XERATH_E_Radius = 60,
	XERATH_E_MissileSpeed = 1400,
	XERATH_E_FixedRange = true,
	XERATH_E_AddHitbox = true,
	XERATH_E_DangerValue = 2,
	XERATH_E_IsDangerous = true,
	//XERATH_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	XERATH_E_CanBeRemoved = true,
	//XERATH_E_CollisionObjects = new[] {CollisionObjectTypes.Minion, CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

	XERATH_R_Delay = 700,
	XERATH_R_Range = 5600,
	XERATH_R_Radius = 130,
	//XERATH_R_MissileSpeed = int.MaxValue,
	XERATH_R_FixedRange = false,
	XERATH_R_AddHitbox = true,
	XERATH_R_DangerValue = 3,
	XERATH_R_IsDangerous = true,

//==57===MALZAHAR==========================================================================================================
	MALZAHAR_Q_Delay = 750,
	MALZAHAR_Q_DelayFlying = 1250,
	MALZAHAR_Q_Range = 300,
	MALZAHAR_Q_Range2 = 350,
	MALZAHAR_Q_Radius = 85,
	//MALZAHAR_Q_MissileSpeed = int.MaxValue,
	MALZAHAR_Q_FixedRange = false,
	MALZAHAR_Q_AddHitbox = true,
	MALZAHAR_Q_DangerValue = 2,
	MALZAHAR_Q_IsDangerous = false,
	MALZAHAR_Q_DontCross = true,

//==58===QUINN==========================================================================================================
	QUINN_Q_Delay = 313,
	//QUINN_Q_Range = 1050,
	QUINN_Q_Range = 500,
	QUINN_Q_Radius = 60,
	QUINN_Q_MissileSpeed = 1550,
	QUINN_Q_FixedRange = true,
	QUINN_Q_AddHitbox = true,
	QUINN_Q_DangerValue = 2,
	QUINN_Q_IsDangerous = false,
	//QUINN_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	QUINN_Q_CanBeRemoved = true,
	//QUINN_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

//==59===ANIVIA==========================================================================================================
	ANIVIA_Q_Delay = 250,
	ANIVIA_Q_Range = 1100,
	ANIVIA_Q_Radius = 110,
	ANIVIA_Q_MissileSpeed = 850,
	ANIVIA_Q_FixedRange = true,
	ANIVIA_Q_AddHitbox = true,
	ANIVIA_Q_DangerValue = 3,
	ANIVIA_Q_IsDangerous = true,
	//ANIVIA_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.AllyObjects},
	ANIVIA_Q_CanBeRemoved = true,
	//ANIVIA_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}

	ANIVIA_R_Delay = 250,
	ANIVIA_R_MissileSpeed = 1600,
	ANIVIA_R_Radius = 400,
	ANIVIA_R_Range = 625,

//==60===ZYRA==========================================================================================================
	ZYRA_Q_Delay = 850,
	ZYRA_Q_DelayFlying = 1250,
	ZYRA_Q_Range = 400,
	ZYRA_Q_Radius = 85,
	//ZYRA_Q_MissileSpeed = int.MaxValue,
	ZYRA_Q_FixedRange = false,
	ZYRA_Q_AddHitbox = true,
	ZYRA_Q_DangerValue = 2,
	ZYRA_Q_IsDangerous = false,

	ZYRA_E_Delay = 250,
	ZYRA_E_Range = 1150,
	ZYRA_E_Radius = 70,
	ZYRA_E_MissileSpeed = 1150,
	ZYRA_E_FixedRange = true,
	ZYRA_E_AddHitbox = true,
	ZYRA_E_DangerValue = 3,
	ZYRA_E_IsDangerous = true,
	//ZYRA_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	//ZYRA_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	ZYRA_R_Delay = 250,
	ZYRA_R_DelayFlying = 400,
	ZYRA_R_Range = 1474,
	ZYRA_R_Radius = 500,
	ZYRA_R_MissileSpeed = 2000,
	ZYRA_R_FixedRange = true,
	ZYRA_R_AddHitbox = true,
	ZYRA_R_DangerValue = 3,
	ZYRA_R_IsDangerous = true,
	//ZYRA_R_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	//ZYRA_R_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==61===ELISE==========================================================================================================
	ELISE_W_Range = 950,
	ELISE_W_Radius = 100,
	
	ELISE_E_Delay = 250,
	ELISE_E_Range = 1100,
	ELISE_E_Radius = 55,
	ELISE_E_MissileSpeed = 1600,
	ELISE_E_FixedRange = true,
	ELISE_E_AddHitbox = true,
	ELISE_E_DangerValue = 4,
	ELISE_E_IsDangerous = true,
	//ELISE_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	ELISE_E_CanBeRemoved = true,
	//ELISE_E_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall}

//==62===EVELYNN==========================================================================================================
	EVELYNN_R_Delay = 250,
	EVELYNN_R_Range = 650,
	EVELYNN_R_Radius = 350,
	EVELYNN_R_MissileSpeed = 1300,
	EVELYNN_R_FixedRange = false,
	EVELYNN_R_AddHitbox = true,
	EVELYNN_R_DangerValue = 5,
	EVELYNN_R_IsDangerous = true,

//==63===DIANA==========================================================================================================
	DIANA_Q_Delay = 250,
	DIANA_Q_Range = 895,
	DIANA_Q_Radius = 195,
	DIANA_Q_MissileSpeed = 1400,
	DIANA_Q_FixedRange = false,
	DIANA_Q_AddHitbox = true,
	DIANA_Q_DangerValue = 3,
	DIANA_Q_IsDangerous = true,
	//DIANA_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.AllyObjects},
	//DIANA_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}

//==64===KENNEN==========================================================================================================
	KENNEN_Q_Delay = 125,
	KENNEN_Q_Range = 1050,
	KENNEN_Q_Radius = 50,
	KENNEN_Q_MissileSpeed = 1700,
	KENNEN_Q_FixedRange = true,
	KENNEN_Q_AddHitbox = true,
	KENNEN_Q_DangerValue = 2,
	KENNEN_Q_IsDangerous = false,
	//KENNEN_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	KENNEN_Q_CanBeRemoved = true,
	//KENNEN_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

//==65===POPPY==========================================================================================================
	POPPY_Q_Delay = 500,
	POPPY_Q_Range = 430,
	POPPY_Q_Radius = 100,
	//POPPY_Q_MissileSpeed = int.MaxValue,
	POPPY_Q_FixedRange = true,
	POPPY_Q_AddHitbox = true,
	POPPY_Q_DangerValue = 2,
	POPPY_Q_IsDangerous = false,
	//POPPY_Q_EarlyEvade = new[] { EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects },

	POPPY_R_Delay = 300,
	POPPY_R_Range = 1200,
	POPPY_R_Radius = 90,
	POPPY_R_MissileSpeed = 1600,
	POPPY_R_FixedRange = true,
	POPPY_R_AddHitbox = true,
	POPPY_R_DangerValue = 3,
	POPPY_R_IsDangerous = true,
	POPPY_R_CanBeRemoved = true,
	//POPPY_R_CollisionObjects = new[] { CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall },
//==66===LEBLANC==========================================================================================================
	LEBLANC_W_Delay = 0,
	LEBLANC_W_Range = 600,
	LEBLANC_W_Radius = 220,
	LEBLANC_W_MissileSpeed = 1450,
	LEBLANC_W_FixedRange = false,
	LEBLANC_W_AddHitbox = true,
	LEBLANC_W_DangerValue = 2,
	LEBLANC_W_IsDangerous = false,

	LEBLANC_E_Delay = 250,
	LEBLANC_E_DelayFlying = 500,
	LEBLANC_E_Range = 950,
	LEBLANC_E_Radius = 55,
	LEBLANC_E_MissileSpeed = 1750,
	LEBLANC_E_FixedRange = true,
	LEBLANC_E_AddHitbox = true,
	LEBLANC_E_DangerValue = 3,
	LEBLANC_E_IsDangerous = true,
	//LEBLANC_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	LEBLANC_E_CanBeRemoved = true,
	//LEBLANC_E_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

//==67===BARD==========================================================================================================
	BARD_Q_Delay = 250,
	BARD_Q_Range = 950,
	BARD_Q_Radius = 60,
	BARD_Q_MissileSpeed = 1600,
	BARD_Q_FixedRange = true,
	BARD_Q_AddHitbox = true,
	BARD_Q_DangerValue = 3,
	BARD_Q_IsDangerous = true,
	//BARD_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	BARD_Q_CanBeRemoved = true,
	//BARD_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall}

	BARD_R_Delay = 500,
	BARD_R_Range = 3400,
	BARD_R_Radius = 350,
	BARD_R_MissileSpeed = 2100,
	BARD_R_FixedRange = false,
	BARD_R_AddHitbox = true,
	BARD_R_DangerValue = 2,
	BARD_R_IsDangerous = false,

//==68===ZILEAN==========================================================================================================
	ZILEAN_Q_Delay = 300,
	ZILEAN_Q_Range = 900,
	ZILEAN_Q_Radius = 280,
	ZILEAN_Q_MissileSpeed = 2000,
	ZILEAN_Q_FixedRange = false,
	ZILEAN_Q_AddHitbox = true,
	ZILEAN_Q_DangerValue = 2,
	ZILEAN_Q_IsDangerous = false,
	//ZILEAN_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall}

//==69===LISSANDRA==========================================================================================================
	LISSANDRA_Q_Delay = 250,
	LISSANDRA_Q_Range = 1000,
	LISSANDRA_Q_Radius = 85,
	LISSANDRA_Q_MissileSpeed = 2200,
	LISSANDRA_Q_FixedRange = true,
	LISSANDRA_Q_AddHitbox = true,
	LISSANDRA_Q_DangerValue = 2,
	LISSANDRA_Q_IsDangerous = false,
	//LISSANDRA_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	LISSANDRA_E_Delay = 250,
	LISSANDRA_E_Range = 1100,
	LISSANDRA_E_Radius = 125,
	LISSANDRA_E_MissileSpeed = 850,
	LISSANDRA_E_FixedRange = true,
	LISSANDRA_E_AddHitbox = true,
	LISSANDRA_E_DangerValue = 2,
	LISSANDRA_E_IsDangerous = false,
	//LISSANDRA_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==70===SWAIN==========================================================================================================
	SWAIN_W_Delay = 1100,
	SWAIN_W_Range = 900,
	SWAIN_W_Radius = 200,
	//SWAIN_W_MissileSpeed = int.MaxValue,
	SWAIN_W_FixedRange = false,
	SWAIN_W_AddHitbox = true,
	SWAIN_W_DangerValue = 3,
	SWAIN_W_IsDangerous = true,
//==71===AURELION SOL==========================================================================================================
	AURELIONSOL_Q_Delay = 250,
	AURELIONSOL_Q_Range = 1500,
	AURELIONSOL_Q_Radius = 180,
	AURELIONSOL_Q_MissileSpeed = 850,
	AURELIONSOL_Q_FixedRange = true,
	AURELIONSOL_Q_AddHitbox = true,
	AURELIONSOL_Q_DangerValue = 2,
	AURELIONSOL_Q_IsDangerous = false,
	AURELIONSOL_Q_CanBeRemoved = true,
	//AURELIONSOL_Q_CollisionObjects = new[] { CollisionObjectTypes.YasuoWall},

	AURELIONSOL_R_Delay = 300,
	AURELIONSOL_R_Range = 1500,
	AURELIONSOL_R_Radius = 130,
	AURELIONSOL_R_MissileSpeed = 4500,
	AURELIONSOL_R_FixedRange = true,
	AURELIONSOL_R_AddHitbox = true,
	AURELIONSOL_R_DangerValue = 3,
	AURELIONSOL_R_IsDangerous = true,
	AURELIONSOL_R_CanBeRemoved = true,
	//AURELIONSOL_R_CollisionObjects = new[] { CollisionObjectTypes.YasuoWall},

//==72===TWITCH==========================================================================================================
	TWITCH_W_Delay = 250,
	TWITCH_W_Range = 900,
	TWITCH_W_Radius = 275,
	TWITCH_W_MissileSpeed = 1400,
	TWITCH_W_FixedRange = false,
	TWITCH_W_AddHitbox = true,
	TWITCH_W_DangerValue = 2,
	TWITCH_W_IsDangerous = false,
	//TWITCH_W_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==73===GNAR==========================================================================================================
	GNAR_Q_Delay = 250,
	GNAR_Q_DelayFlying = 400,
	GNAR_Q_Range = 1125,
	GNAR_Q_Radius = 75,
	GNAR_Q_MissileSpeed = 2500,
	GNAR_Q_FixedRange = true,
	GNAR_Q_AddHitbox = true,
	GNAR_Q_DangerValue = 2,
	GNAR_Q_IsDangerous = false,
	GNAR_Q_CanBeRemoved = true,
	GNAR_Q_ForceRemove = true,

	GNAR_QBig_Delay = 500,
	GNAR_QBig_Range = 1150,
	GNAR_QBig_Radius = 90,
	GNAR_QBig_MissileSpeed = 2100,
	GNAR_QBig_FixedRange = true,
	GNAR_QBig_AddHitbox = true,
	GNAR_QBig_DangerValue = 2,
	GNAR_QBig_IsDangerous = false,
	//GNAR_QBig_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	//GNAR_QBig_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	GNAR_WBig_Delay = 600,
	GNAR_WBig_Range = 525,
	GNAR_WBig_Radius = 80,
	//GNAR_WBig_MissileSpeed = int.MaxValue,
	GNAR_WBig_FixedRange = true,
	GNAR_WBig_AddHitbox = true,
	GNAR_WBig_DangerValue = 2,
	GNAR_WBig_IsDangerous = false,

	GNAR_R_Delay = 250,
	GNAR_R_Range = 0,
	GNAR_R_Radius = 500,
	//GNAR_R_MissileSpeed = int.MaxValue,
	GNAR_R_FixedRange = true,
	GNAR_R_AddHitbox = false,
	GNAR_R_DangerValue = 5,
	GNAR_R_IsDangerous = true,
//==74===KOGMAW==========================================================================================================
	KOGMAW_Q_Delay = 250,
	KOGMAW_Q_Range = 1200,
	KOGMAW_Q_Radius = 70,
	KOGMAW_Q_MissileSpeed = 1650,
	KOGMAW_Q_FixedRange = true,
	KOGMAW_Q_AddHitbox = true,
	KOGMAW_Q_DangerValue = 2,
	KOGMAW_Q_IsDangerous = false,
	//KOGMAW_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	KOGMAW_Q_CanBeRemoved = true,
	//KOGMAW_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

	KOGMAW_E_Delay = 250,
	KOGMAW_E_Range = 1300,
	KOGMAW_E_Radius = 120,
	KOGMAW_E_MissileSpeed = 1400,
	KOGMAW_E_FixedRange = true,
	KOGMAW_E_AddHitbox = true,
	KOGMAW_E_DangerValue = 2,
	KOGMAW_E_IsDangerous = false,
	//KOGMAW_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	KOGMAW_R_Delay = 1200,
	KOGMAW_R_Range = 1800,
	KOGMAW_R_Radius = 225,
	//KOGMAW_R_MissileSpeed = int.MaxValue,
	KOGMAW_R_FixedRange = false,
	KOGMAW_R_AddHitbox = true,
	KOGMAW_R_DangerValue = 2,
	KOGMAW_R_IsDangerous = false,

//==75===SINGED==========================================================================================================
	SINGED_W_Delay = 250,
	SINGED_W_ForceRemove = false,
	SINGED_W_IsDangerous = false,
	SINGED_W_MissileSpeed = 1000,
	SINGED_W_Radius = 250,
	SINGED_W_Range = 1000,

//==76===CASSIOPEIA==========================================================================================================
	CASSIOPEIA_Q_Delay = 750,
	CASSIOPEIA_Q_Range = 850,
	CASSIOPEIA_Q_Radius = 150,
	//CASSIOPEIA_Q_MissileSpeed = int.MaxValue,
	CASSIOPEIA_Q_FixedRange = false,
	CASSIOPEIA_Q_AddHitbox = true,
	CASSIOPEIA_Q_DangerValue = 2,
	CASSIOPEIA_Q_IsDangerous = false,

	CASSIOPEIA_W_DelayFlying = 650,
	CASSIOPEIA_W_RangeCircle1 = 500,
	CASSIOPEIA_W_RangeCircle2 = 880,
	CASSIOPEIA_W_RangeLine = 400,
	CASSIOPEIA_W_RadiusLine = 120,

	CASSIOPEIA_R_DelayFlying = 200,
	CASSIOPEIA_R_Range = 825,
	CASSIOPEIA_R_RadiusLine = 30,
	CASSIOPEIA_R_RadiusCone = 680,
	//CASSIOPEIA_R_MissileSpeed = int.MaxValue,
	CASSIOPEIA_R_FixedRange = false,
	CASSIOPEIA_R_AddHitbox = false,
	CASSIOPEIA_R_DangerValue = 5,
	CASSIOPEIA_R_IsDangerous = true,

//==77===HEIMERDINGER==========================================================================================================
	HEIMERDINGER_W_Delay = 250,
	HEIMERDINGER_W_Range = 1350,
	HEIMERDINGER_W_Radius = 180,
	HEIMERDINGER_W_MissileSpeed = 1800,
	HEIMERDINGER_W_FixedRange = true,
	HEIMERDINGER_W_AddHitbox = true,
	HEIMERDINGER_W_DangerValue = 2,
	HEIMERDINGER_W_IsDangerous = false,
	//HEIMERDINGER_W_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	HEIMERDINGER_E_Delay = 250,
	HEIMERDINGER_E_Range = 925,
	HEIMERDINGER_E_Radius = 100,
	HEIMERDINGER_E_MissileSpeed = 1200,
	HEIMERDINGER_E_FixedRange = false,
	HEIMERDINGER_E_AddHitbox = true,
	HEIMERDINGER_E_DangerValue = 2,
	HEIMERDINGER_E_IsDangerous = false,
	//HEIMERDINGER_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	HEIMERDINGER_RE_Range = 1200,
	HEIMERDINGER_RE_Radius = 220,

//==78===ILLAOI==========================================================================================================
	ILLAOI_Q_Delay = 750,
	ILLAOI_Q_Range = 850,
	ILLAOI_Q_Radius = 100,
	//ILLAOI_Q_MissileSpeed = int.MaxValue,
	ILLAOI_Q_FixedRange = true,
	ILLAOI_Q_AddHitbox = true,
	ILLAOI_Q_DangerValue = 3,
	ILLAOI_Q_IsDangerous = true,
	//ILLAOI_Q_CollisionObjects = new[] { CollisionObjectTypes.YasuoWall },

	ILLAOI_E_Delay = 250,
	ILLAOI_E_Range = 950,
	ILLAOI_E_Radius = 50,
	ILLAOI_E_MissileSpeed = 1900,
	ILLAOI_E_FixedRange = true,
	ILLAOI_E_AddHitbox = true,
	ILLAOI_E_DangerValue = 3,
	ILLAOI_E_IsDangerous = true,
	//ILLAOI_E_CollisionObjects = new[] { CollisionObjectTypes.YasuoWall },

	ILLAOI_R_Delay = 500,
	ILLAOI_R_Range = 0,
	ILLAOI_R_Radius = 450,
	//ILLAOI_R_MissileSpeed = int.MaxValue,
	ILLAOI_R_FixedRange = true,
	ILLAOI_R_AddHitbox = false,
	ILLAOI_R_DangerValue = 3,
	ILLAOI_R_IsDangerous = true,

//==79===LEONA==========================================================================================================
	LEONA_E_Delay = 250,
	LEONA_E_Range = 905,
	LEONA_E_Radius = 70,
	LEONA_E_MissileSpeed = 2000,
	LEONA_E_FixedRange = true,
	LEONA_E_AddHitbox = true,
	LEONA_E_DangerValue = 3,
	LEONA_E_IsDangerous = true,
	LEONA_E_TakeClosestPath = true,
	//LEONA_E_EarlyEvade = new[] {EarlyObjects.Allies},
	//LEONA_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	LEONA_R_Delay = 1000,
	LEONA_R_Range = 1200,
	LEONA_R_Radius = 300,
	//LEONA_R_MissileSpeed = int.MaxValue,
	LEONA_R_FixedRange = false,
	LEONA_R_AddHitbox = true,
	LEONA_R_DangerValue = 5,
	LEONA_R_IsDangerous = true,

//==80===JAYCE==========================================================================================================
	JAYCE_Q_Delay = 250,
	JAYCE_Q_Range = 1750,
	JAYCE_Q_Radius = 70,
	JAYCE_Q_MissileSpeed = 1450,
	JAYCE_Q_FixedRange = true,
	JAYCE_Q_AddHitbox = true,
	JAYCE_Q_DangerValue = 2,
	JAYCE_Q_IsDangerous = false,
	//JAYCE_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	JAYCE_Q_CanBeRemoved = true,
	//JAYCE_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

//==81===KASSADIN==========================================================================================================
	KASSADIN_E_Range = 585,
	KASSADIN_E_RadiusLine = 30,
	KASSADIN_E_RadiusCone = 400,
	KASSADIN_E_DelayFlying = 150,

	KASSADIN_R_Delay = 250,
	KASSADIN_R_Range = 450,
	KASSADIN_R_Radius = 270,
	//KASSADIN_R_MissileSpeed = int.MaxValue,
	KASSADIN_R_FixedRange = false,
	KASSADIN_R_AddHitbox = true,
	KASSADIN_R_DangerValue = 2,
	KASSADIN_R_IsDangerous = false,

//==82===SHEN==========================================================================================================
	SHEN_E_Delay = 0,
	SHEN_E_Range = 650,
	SHEN_E_Radius = 50,
	SHEN_E_MissileSpeed = 1600,
	SHEN_E_FixedRange = false,
	SHEN_E_AddHitbox = true,
	SHEN_E_DangerValue = 3,
	SHEN_E_IsDangerous = true,
	SHEN_E_ExtraRange = 200,
	//SHEN_E_CollisionObjects = new[] {CollisionObjectTypes.Minion, CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

//==83===VIKTOR==========================================================================================================
	VIKTOR_W_Radius = 300,
	
	VIKTOR_E_Delay = 250,
	VIKTOR_E_Range = 1500,
	VIKTOR_E_Radius = 80,
	VIKTOR_E_MissileSpeed = 1050,
	VIKTOR_E_FixedRange = false,
	VIKTOR_E_AddHitbox = true,
	VIKTOR_E_DangerValue = 2,
	VIKTOR_E_IsDangerous = false,
	//VIKTOR_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},
	
	VIKTOR_R_Radius = 300,

//==84===GANGPLANK==========================================================================================================
	GANGPLANK_R_Radius = 600,

//==85===NAMI==========================================================================================================
	NAMI_Q_Delay = 950,
	NAMI_Q_Range = 1625,
	NAMI_Q_Radius = 150,
	//NAMI_Q_MissileSpeed = int.MaxValue,
	NAMI_Q_FixedRange = false,
	NAMI_Q_AddHitbox = true,
	NAMI_Q_DangerValue = 3,
	NAMI_Q_IsDangerous = true,

	NAMI_R_Delay = 500,
	NAMI_R_Range = 2750,
	NAMI_R_Radius = 260,
	NAMI_R_MissileSpeed = 850,
	NAMI_R_FixedRange = true,
	NAMI_R_AddHitbox = true,
	NAMI_R_DangerValue = 2,
	NAMI_R_IsDangerous = false,
	//NAMI_R_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==86===PHANTHEON==========================================================================================================
	PHANTHEON_E_Range = 675,
	PHANTHEON_E_RadiusLine = 30,
	PHANTHEON_E_RadiusCone = 400,
	PHANTHEON_E_DelayFlying = 150,

	PHANTHEON_R_DelayFlyingJump = 550,
	PHANTHEON_R_DelayFlyingFall = 550,
	PHANTHEON_R_Radius = 550,

//==87===MAOKAI==========================================================================================================
	MAOKAI_Q_Delay = 250,
	MAOKAI_Q_RadiusCircle = 210,
	MAOKAI_Q_RadiusLine = 80,
	MAOKAI_Q_Range = 600,

	MAOKAI_E_Radius = 200,

//==88===RENGAR==========================================================================================================
	RENGAR_E_Delay = 250,
	RENGAR_E_Range = 1000,
	RENGAR_E_Radius = 70,
	RENGAR_E_MissileSpeed = 1500,
	RENGAR_E_FixedRange = true,
	RENGAR_E_AddHitbox = true,
	RENGAR_E_DangerValue = 3,
	RENGAR_E_IsDangerous = true,
	//RENGAR_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	RENGAR_E_CanBeRemoved = true,
	//RENGAR_E_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

//==89===REKSAI==========================================================================================================
	REKSAI_Q_Delay = 500,
	REKSAI_Q_Range = 1625,
	REKSAI_Q_Radius = 60,
	REKSAI_Q_MissileSpeed = 1950,
	REKSAI_Q_FixedRange = true,
	REKSAI_Q_AddHitbox = true,
	REKSAI_Q_DangerValue = 3,
	REKSAI_Q_IsDangerous = false,
	//REKSAI_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	//REKSAI_Q_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

//==90===SKARNER==========================================================================================================
	SKARNER_E_Delay = 250,
	SKARNER_E_Range = 1050,
	SKARNER_E_Radius = 70,
	SKARNER_E_MissileSpeed = 1500,
	SKARNER_E_FixedRange = true,
	SKARNER_E_AddHitbox = true,
	SKARNER_E_DangerValue = 2,
	SKARNER_E_IsDangerous = false,
	//SKARNER_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

//==91===TARIC==========================================================================================================
	TARIC_E_Delay = 1000,
	TARIC_E_Range = 750,
	TARIC_E_Radius = 100,
	//TARIC_E_MissileSpeed = int.MaxValue,
	TARIC_E_FixedRange = true,
	TARIC_E_AddHitbox = true,
	TARIC_E_DangerValue = 3,
	TARIC_E_IsDangerous = true,

//==92===VI==========================================================================================================
	VI_Q_Delay = 250,
	VI_Q_Range = 1000,
	VI_Q_Radius = 55,
	VI_Q_MissileSpeed = 1500,
	VI_Q_FixedRange = true,
	VI_Q_AddHitbox = true,
	VI_Q_DangerValue = 3,
	VI_Q_IsDangerous = true,

//==93===TEEMO==========================================================================================================
	TEEMO_R_Radius = 135,

//==94===URGOT==========================================================================================================
	URGOT_Q_Delay = 125,
	URGOT_Q_Range = 1000,
	URGOT_Q_Radius = 60,
	URGOT_Q_MissileSpeed = 1600,
	URGOT_Q_FixedRange = true,
	URGOT_Q_AddHitbox = true,
	URGOT_Q_DangerValue = 2,
	URGOT_Q_IsDangerous = false,
	//URGOT_Q_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	URGOT_Q_CanBeRemoved = true,

	URGOT_E_Delay = 250,
	URGOT_E_Range = 1100,
	URGOT_E_Radius = 210,
	URGOT_E_MissileSpeed = 1500,
	URGOT_E_FixedRange = false,
	URGOT_E_AddHitbox = true,
	URGOT_E_DangerValue = 2,
	URGOT_E_IsDangerous = false,
//==95===ORIANNA==========================================================================================================
	ORIANNA_Q_Delay = 0,
	ORIANNA_Q_Range = 1500,
	ORIANNA_Q_Radius = 80,
	ORIANNA_Q_MissileSpeed = 1200,
	ORIANNA_Q_FixedRange = false,
	ORIANNA_Q_AddHitbox = true,
	ORIANNA_Q_DangerValue = 2,
	ORIANNA_Q_IsDangerous = false,
	//ORIANNA_Q_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	ORIANNA_QEND_Delay = 0,
	ORIANNA_QEND_Range = 1500,
	ORIANNA_QEND_Radius = 90,
	ORIANNA_QEND_MissileSpeed = 1200,
	ORIANNA_QEND_FixedRange = false,
	ORIANNA_QEND_AddHitbox = true,
	ORIANNA_QEND_DangerValue = 2,
	ORIANNA_QEND_IsDangerous = false,
	//ORIANNA_QEND_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	ORIANNA_W_Delay = 250,
	ORIANNA_W_Range = 0,
	ORIANNA_W_Radius = 255,
	//ORIANNA_W_MissileSpeed = int.MaxValue,
	ORIANNA_W_FixedRange = true,
	ORIANNA_W_AddHitbox = true,
	ORIANNA_W_DangerValue = 2,
	ORIANNA_W_IsDangerous = false,

	ORIANNA_E_Delay = 0,
	ORIANNA_E_Range = 1500,
	ORIANNA_E_Radius = 85,
	ORIANNA_E_MissileSpeed = 1850,
	ORIANNA_E_FixedRange = false,
	ORIANNA_E_AddHitbox = true,
	ORIANNA_E_DangerValue = 2,
	ORIANNA_E_IsDangerous = false,
	//ORIANNA_E_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	ORIANNA_R_Delay = 700,
	ORIANNA_R_Range = 0,
	ORIANNA_R_Radius = 410,
	//ORIANNA_R_MissileSpeed = int.MaxValue,
	ORIANNA_R_FixedRange = true,
	ORIANNA_R_AddHitbox = true,
	ORIANNA_R_DangerValue = 5,
	ORIANNA_R_IsDangerous = true,

//==96===RUMBLE==========================================================================================================
	RUMBLE_E_Delay = 250,
	RUMBLE_E_Range = 950,
	RUMBLE_E_Radius = 60,
	RUMBLE_E_MissileSpeed = 2000,
	RUMBLE_E_FixedRange = true,
	RUMBLE_E_AddHitbox = true,
	RUMBLE_E_DangerValue = 2,
	RUMBLE_E_IsDangerous = false,
	//RUMBLE_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	RUMBLE_E_CanBeRemoved = true,
	//RUMBLE_E_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.Minion, CollisionObjectTypes.YasuoWall},

	RUMBLE_R_Delay = 400,
	RUMBLE_R_MissileDelayed = true,
	RUMBLE_R_Range = 1200,
	RUMBLE_R_Radius = 150,
	RUMBLE_R_MissileSpeed = 1600,
	RUMBLE_R_FixedRange = true,
	RUMBLE_R_AddHitbox = true,
	RUMBLE_R_DangerValue = 4,
	RUMBLE_R_IsDangerous = false,
	RUMBLE_R_CanBeRemoved = false,
	//RUMBLE_R_CollisionObjects = new CollisionObjectTypes[] {},

//==97===SHYVANA==========================================================================================================
	SHYVANA_E_Delay = 250,
	SHYVANA_E_Range = 950,
	SHYVANA_E_Radius = 60,
	SHYVANA_E_MissileSpeed = 1700,
	SHYVANA_E_FixedRange = true,
	SHYVANA_E_AddHitbox = true,
	SHYVANA_E_DangerValue = 2,
	SHYVANA_E_IsDangerous = false,
	//SHYVANA_E_EarlyEvade = new[] {EarlyObjects.Allies, EarlyObjects.Minions, EarlyObjects.AllyObjects},
	//SHYVANA_E_CollisionObjects = new[] {CollisionObjectTypes.Minion, CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

	SHYVANA_E2_Delay = 250,
	SHYVANA_E2_Range = 850,
	SHYVANA_E2_Radius = 150,
	SHYVANA_E2_MissileSpeed = 2000,
	SHYVANA_E2_FixedRange = true,
	SHYVANA_E2_AddHitbox = true,
	SHYVANA_E2_DangerValue = 3,
	SHYVANA_E2_IsDangerous = false,
	SHYVANA_E2_ExtraRange = 200,
	SHYVANA_E2_MultipleNumber = 5,
	//SHYVANA_E2_MultipleAngle = 10 * (float)Math.PI / 180

	SHYVANA_R_Delay = 250,
	SHYVANA_R_Range = 1000,
	SHYVANA_R_Radius = 180,
	SHYVANA_R_MissileSpeed = 1500,
	SHYVANA_R_FixedRange = true,
	SHYVANA_R_AddHitbox = true,
	SHYVANA_R_DangerValue = 3,
	SHYVANA_R_IsDangerous = true,
	SHYVANA_R_ExtraRange = 200,

//==98===SION==========================================================================================================
	SION_Q_DelayFlying = 400,
	SION_Q_Range = 600,
	SION_Q_Radius = 200,
	
	SION_E_Delay = 250,
	SION_E_Range = 1000,
	SION_E_Radius = 80,
	SION_E_MissileSpeed = 1800,
	SION_E_FixedRange = true,
	SION_E_AddHitbox = true,
	SION_E_DangerValue = 3,
	SION_E_IsDangerous = true,
	//SION_E_CollisionObjects = new[] {CollisionObjectTypes.Champions, CollisionObjectTypes.YasuoWall},

	SION_R_Delay = 500,
	SION_R_Range = 2000,
	SION_R_Radius = 150,
	SION_R_MissileSpeed = 1000,
	SION_R_FixedRange = true,
	SION_R_AddHitbox = true,
	SION_R_DangerValue = 3,
	SION_R_IsDangerous = true,
	//SION_R_EarlyEvade = new[] {EarlyObjects.Allies},
	//SION_R_CollisionObjects = new[] {CollisionObjectTypes.Champions},

//==99===SYNDRA==========================================================================================================
	SYNDRA_Q_Delay = 600,
	SYNDRA_Q_Range = 800,
	SYNDRA_Q_Radius = 150,
	//SYNDRA_Q_MissileSpeed = int.MaxValue,
	SYNDRA_Q_FixedRange = false,
	SYNDRA_Q_AddHitbox = true,
	SYNDRA_Q_DangerValue = 2,
	SYNDRA_Q_IsDangerous = false,

	SYNDRA_W_Delay = 250,
	SYNDRA_W_Range = 950,
	SYNDRA_W_Radius = 210,
	SYNDRA_W_MissileSpeed = 1450,
	SYNDRA_W_FixedRange = false,
	SYNDRA_W_AddHitbox = true,
	SYNDRA_W_DangerValue = 2,
	SYNDRA_W_IsDangerous = false,

	SYNDRA_E_Delay = 0,
	SYNDRA_E_Range = 950,
	SYNDRA_E_Radius = 100,
	SYNDRA_E_MissileSpeed = 2000,
	SYNDRA_E_FixedRange = false,
	SYNDRA_E_AddHitbox = true,
	SYNDRA_E_DangerValue = 2,
	SYNDRA_E_IsDangerous = false,
	SYNDRA_E_DisableFowDetection = true,

//=100===VLADIMIR==========================================================================================================
	VLADIMIR_R_Radius = 200,

//=101===ZIGGS==========================================================================================================
	ZIGGS_Q_Delay = 250,
	ZIGGS_Q_Range = 850,
	ZIGGS_Q_Range2 = 700,
	ZIGGS_Q_Radius = 50,
	ZIGGS_Q_MissileSpeed = 1700,
	ZIGGS_Q_FixedRange = false,
	ZIGGS_Q_AddHitbox = true,
	ZIGGS_Q_DangerValue = 2,
	ZIGGS_Q_IsDangerous = false,
	ZIGGS_Q_CanBeRemoved = false,
	ZIGGS_Q_DisableFowDetection = true,

	ZIGGS_W_Delay = 250,
	ZIGGS_W_Range = 1000,
	ZIGGS_W_Radius = 275,
	ZIGGS_W_MissileSpeed = 1750,
	ZIGGS_W_FixedRange = false,
	ZIGGS_W_AddHitbox = true,
	ZIGGS_W_DangerValue = 2,
	ZIGGS_W_IsDangerous = false,
	ZIGGS_W_DisableFowDetection = true,
	//ZIGGS_W_CollisionObjects = new[] {CollisionObjectTypes.YasuoWall},

	ZIGGS_E_Delay = 500,
	ZIGGS_E_Range = 900,
	ZIGGS_E_Radius = 235,
	ZIGGS_E_MissileSpeed = 1750,
	ZIGGS_E_FixedRange = false,
	ZIGGS_E_AddHitbox = true,
	ZIGGS_E_DangerValue = 2,
	ZIGGS_E_IsDangerous = false,
	ZIGGS_E_DisableFowDetection = true,

	ZIGGS_R_Delay = 0,
	ZIGGS_R_Range = 5300,
	ZIGGS_R_Radius = 500,
	//ZIGGS_R_MissileSpeed = int.MaxValue,
	ZIGGS_R_FixedRange = false,
	ZIGGS_R_AddHitbox = true,
	ZIGGS_R_DangerValue = 2,
	ZIGGS_R_IsDangerous = false,
	ZIGGS_R_DisableFowDetection = true,

//=102===ZAC==========================================================================================================
	ZAC_Q_Delay = 500,
	ZAC_Q_Range = 550,
	ZAC_Q_Radius = 120,
	//ZAC_Q_MissileSpeed = int.MaxValue,
	ZAC_Q_FixedRange = true,
	ZAC_Q_AddHitbox = true,
	ZAC_Q_DangerValue = 2,
	ZAC_Q_IsDangerous = false,

//=103===ANNIE==========================================================================================================
	ANNIE_W_DelayFlying = 150,
	ANNIE_W_Range = 650,
	ANNIE_W_RadiusCone = 300,
	ANNIE_W_RadiusLine = 30,
	//ANNIE_W_MissileSpeed = int.MaxValue,
	ANNIE_W_FixedRange = false,
	ANNIE_W_AddHitbox = false,
	ANNIE_W_DangerValue = 2,
	ANNIE_W_IsDangerous = false,

	ANNIE_R_Delay = 250,
	ANNIE_R_DelayFlying = 200,
	ANNIE_R_Range = 600,
	ANNIE_R_Radius = 351,
	//ANNIE_R_MissileSpeed = int.MaxValue,
	ANNIE_R_FixedRange = false,
	ANNIE_R_AddHitbox = true,
	ANNIE_R_DangerValue = 5,
	ANNIE_R_IsDangerous = true,

//=104===MORDEKAISER==========================================================================================================
	MORDEKAISER_E_Range = 650,
	MORDEKAISER_E_RadiusLine = 30,
	MORDEKAISER_E_RadiusCone = 200,
	MORDEKAISER_E_DelayFlying = 150,

//=105===TALON==========================================================================================================
	TALON_W_DelayFlying = 200,
	TALON_W_Range = 800,
	TALON_W_RadiusLine = 30,
	TALON_W_RadiusCone = 360,

//=106===RIVEN==========================================================================================================
	RIVEN_R_DelayFlying = 200,
	RIVEN_R_Range = 1100,
	RIVEN_R_RadiusLine = 30,
	RIVEN_R_RadiusCone = 320,

//=107===TALON==========================================================================================================
//=108===TALON==========================================================================================================
//=109===TALON==========================================================================================================
//=110===TALON==========================================================================================================
};
void SetSpellData(KBuffer_Spell &buffer);
